#!/usr/bin/env zsh

## configs
typeset -A _C
typeset -A _certConf


## certificate config
_certConf=(
  ##certConf "RU\nMO\nMoscow\npron\ns3\ns3.pron.es\nshatfel@gmail.com\n"
  country "RU"
  state "MO"
  city "MSK"
  company "pron.su"
  ou "organizationUnit"
  commonName "pron.su"
  email "shatfel@gmail.com"
  )


## config
_C=(
  ## cert
  certKeyBits 4096

  ## keys
  keysPath "/tmp/gen-certs.$$"
  privateKey "private.key"
  publicKey "public.crt"
  )
