#!/usr/bin/env zsh

##
local _pwd="`pwd`"

## config
local conf="./config"

## load config
. ${conf}

## create temp dir
mkdir -p ${_C[keysPath]}
cd ${_C[keysPath]}

## cert subject
local _certSubj="/C=${_certConf[country]}/ST=${_certConf[state]}/L=${_certConf[city]}/O=${_certConf[company]}/OU=${_certConf[ou]}/CN=${_certConf[commonName]}/emailAddress=${_certConf[email]}" 

## gen certs
openssl \
  req \
  -newkey rsa:${_C[certKeyBits]} -nodes \
  -keyout ${_C[privateKey]} \
  -x509 -days 36500 -out ${_C[publicKey]} \
  -subj "${_certSubj}"


## check certificate
openssl x509 -text -noout -in ${_C[publicKey]}

printf "\n/i/ your keys are here now: ${_C[keysPath]} ..\n"

cd ${_pwd}
